name: 'Alire Setup'
description: 'Install Alire package manager'
author: 'Alire Project'

inputs:
  version:
    description: Use this argument to install a stable release. Use a version number without v prefix, e.g., 1.0.1, 1.1.0. This argument will be ignored if a branch argument is supplied. Defaults to the latest stable release.
    required: false
    default: '1.2.1'
  branch:
    description: Use this argument to install a development branch (e.g., master). Using this option will require a preexisting compiler in the workflow environment.
    required: false
    default: ''
  toolchain:
    description: Arguments to pass to `alr toolchain` after setup.
    required: false
    default: 'gnat_native gprbuild'
  toolchain_dir:
    description: Location to install toolchain under.
    required: false
    default: ''
  use_cache:
    description: Whether to use a cached gnat/alr/toolchain installation from previous action runs.
    required: false
    default: true

runs:
  using: "composite"
  steps:

    # Try to reuse cached GNAT when branch build requested
    - name: Reuse cached GNAT whenever necessary
      if: ${{ inputs.use_cache == 'true' && inputs.branch != '' }}
      id: cache-gnat
      uses: actions/cache@v3
      with:
        path: gnat
        key: gnat-${{ runner.os }}-ce2020-1

    # Install GNAT if branch build. On cache hit the installer just sets the path.
    - name: Install GNAT when alr branch requested
      if: ${{ inputs.branch != '' }}
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: community
        install_dir: gnat

    - shell: bash
      run: |
        which gnat
        gnat --version

    # We don't cache branch builds for now, as this would require to check the head commit
    - name: Reuse cached installation
      if: ${{ inputs.use_cache == 'true' && inputs.branch == '' }}
      id: cache-alr
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/alire
          ~/.config/alire
          ./alire_install
        key: alr-v${{ inputs.version }}-b_${{ inputs.branch }}-t_${{ inputs.toolchain }}-o_${{ runner.os }}
        # .cache contains msys64 install on Windows
        # .config contains the toolchain at the default location, besides index config
        # ./alire_install contains alr itself

    # Restore alr path in case of alr cache hit.
    - if: ${{ steps.cache-alr.outputs.cache-hit == 'true' && runner.os != 'Windows' }}
      shell: bash
      run: echo "$PWD/alire_install/bin" >> $GITHUB_PATH
    - if: ${{ steps.cache-alr.outputs.cache-hit == 'true' && runner.os == 'Windows' }}
      shell: pwsh
      run: Add-Content $env:GITHUB_PATH "${PWD}\alire_install\bin"

    # Or install alr when alr cache miss
    - if: ${{ steps.cache-alr.outputs.cache-hit != 'true' }}
      uses: alire-project/setup-alire@v1  # v1 is the actual installer, uncached
      with:
        version: ${{ inputs.version }}
        branch: ${{ inputs.branch }}
        toolchain: ${{ inputs.toolchain }}
        toolchain_dir: ${{ inputs.toolchain_dir }}

    - shell: bash
      run: |
        which alr
        alr --version